/**
 * Fix SIC-style industry data
 *
 * Detects and repairs:
 * 1. ALL CAPS industry values (SIC codes stored as industry)
 * 2. Cases where sector === industry (same raw SIC value for both)
 * 3. 'Unknown' or null sector/industry
 *
 * Uses a comprehensive ticker → {sector, industry} mapping for S&P 500.
 */

import { prisma } from '../src/lib/db/prisma';

// ─────────────────────────────────────────────────────────────
// COMPREHENSIVE CORRECT MAPPINGS - Yahoo Finance style
// ─────────────────────────────────────────────────────────────
const CORRECT_MAPPINGS: Record<string, { sector: string; industry: string }> = {
  // ── Technology ──────────────────────────────────────────────
  AAPL:  { sector: 'Technology', industry: 'Consumer Electronics' },
  MSFT:  { sector: 'Technology', industry: 'Software—Application' },
  NVDA:  { sector: 'Technology', industry: 'Semiconductors' },
  GOOGL: { sector: 'Technology', industry: 'Internet Content & Information' },
  GOOG:  { sector: 'Technology', industry: 'Internet Content & Information' },
  META:  { sector: 'Technology', industry: 'Internet Content & Information' },
  AVGO:  { sector: 'Technology', industry: 'Semiconductors' },
  TSMC:  { sector: 'Technology', industry: 'Semiconductors' },
  TSM:   { sector: 'Technology', industry: 'Semiconductors' },
  AMD:   { sector: 'Technology', industry: 'Semiconductors' },
  INTC:  { sector: 'Technology', industry: 'Semiconductors' },
  QCOM:  { sector: 'Technology', industry: 'Semiconductors' },
  TXN:   { sector: 'Technology', industry: 'Semiconductors' },
  MU:    { sector: 'Technology', industry: 'Semiconductors' },
  ADI:   { sector: 'Technology', industry: 'Semiconductors' },
  NXPI:  { sector: 'Technology', industry: 'Semiconductors' },
  MRVL:  { sector: 'Technology', industry: 'Semiconductors' },
  MCHP:  { sector: 'Technology', industry: 'Semiconductors' },
  ON:    { sector: 'Technology', industry: 'Semiconductors' },
  SWKS:  { sector: 'Technology', industry: 'Semiconductors' },
  MPWR:  { sector: 'Technology', industry: 'Semiconductors' },
  LRCX:  { sector: 'Technology', industry: 'Semiconductor Equipment' },
  AMAT:  { sector: 'Technology', industry: 'Semiconductor Equipment' },
  ASML:  { sector: 'Technology', industry: 'Semiconductor Equipment' },
  KLAC:  { sector: 'Technology', industry: 'Semiconductor Equipment' },
  CSCO:  { sector: 'Technology', industry: 'Communication Equipment' },
  ANET:  { sector: 'Technology', industry: 'Communication Equipment' },
  JNPR:  { sector: 'Technology', industry: 'Communication Equipment' },
  CRM:   { sector: 'Technology', industry: 'Software—Application' },
  ADBE:  { sector: 'Technology', industry: 'Software—Application' },
  ORCL:  { sector: 'Technology', industry: 'Software—Application' },
  SAP:   { sector: 'Technology', industry: 'Software—Application' },
  SNPS:  { sector: 'Technology', industry: 'Software—Application' },
  CDNS:  { sector: 'Technology', industry: 'Software—Application' },
  FTNT:  { sector: 'Technology', industry: 'Software—Application' },
  PANW:  { sector: 'Technology', industry: 'Software—Application' },
  PLTR:  { sector: 'Technology', industry: 'Software—Application' },
  NET:   { sector: 'Technology', industry: 'Software—Application' },
  SNOW:  { sector: 'Technology', industry: 'Software—Application' },
  TEAM:  { sector: 'Technology', industry: 'Software—Application' },
  WDAY:  { sector: 'Technology', industry: 'Software—Application' },
  ZS:    { sector: 'Technology', industry: 'Software—Application' },
  CRWD:  { sector: 'Technology', industry: 'Software—Application' },
  VEEV:  { sector: 'Technology', industry: 'Software—Application' },
  TTWO:  { sector: 'Technology', industry: 'Software—Application' },
  EA:    { sector: 'Technology', industry: 'Software—Application' },
  ADP:   { sector: 'Technology', industry: 'Information Technology Services' },
  ADSK:  { sector: 'Technology', industry: 'Software—Application' },
  ACN:   { sector: 'Technology', industry: 'Information Technology Services' },
  IBM:   { sector: 'Technology', industry: 'Information Technology Services' },
  INTU:  { sector: 'Technology', industry: 'Software—Application' },
  NOW:   { sector: 'Technology', industry: 'Software—Application' },
  CTSH:  { sector: 'Technology', industry: 'Information Technology Services' },
  HPQ:   { sector: 'Technology', industry: 'Computer Hardware' },
  HPE:   { sector: 'Technology', industry: 'Computer Hardware' },
  DELL:  { sector: 'Technology', industry: 'Computer Hardware' },
  WDC:   { sector: 'Technology', industry: 'Computer Hardware' },
  STX:   { sector: 'Technology', industry: 'Computer Hardware' },
  NTAP:  { sector: 'Technology', industry: 'Computer Hardware' },
  APLE:  { sector: 'Technology', industry: 'Computer Hardware' },
  APH:   { sector: 'Technology', industry: 'Electronic Components' },
  CDW:   { sector: 'Technology', industry: 'Information Technology Services' },
  FSLR:  { sector: 'Technology', industry: 'Solar' },
  ENPH:  { sector: 'Technology', industry: 'Solar' },
  KEYS:  { sector: 'Technology', industry: 'Scientific & Technical Instruments' },

  // ── Communication Services ───────────────────────────────────
  GOOGL2: { sector: 'Communication Services', industry: 'Internet Content & Information' },
  DIS:    { sector: 'Communication Services', industry: 'Entertainment' },
  NFLX:   { sector: 'Communication Services', industry: 'Entertainment' },
  SPOT:   { sector: 'Communication Services', industry: 'Entertainment' },
  PARA:   { sector: 'Communication Services', industry: 'Entertainment' },
  WBD:    { sector: 'Communication Services', industry: 'Entertainment' },
  FOXA:   { sector: 'Communication Services', industry: 'Entertainment' },
  FOX:    { sector: 'Communication Services', industry: 'Entertainment' },
  SONY:   { sector: 'Communication Services', industry: 'Entertainment' },
  VZ:     { sector: 'Communication Services', industry: 'Telecom Services' },
  T:      { sector: 'Communication Services', industry: 'Telecom Services' },
  TMUS:   { sector: 'Communication Services', industry: 'Telecom Services' },
  CMCSA:  { sector: 'Communication Services', industry: 'Entertainment' },
  CHTR:   { sector: 'Communication Services', industry: 'Entertainment' },
  LUMN:   { sector: 'Communication Services', industry: 'Telecom Services' },
  AMX:    { sector: 'Communication Services', industry: 'Telecom Services' },

  // ── Consumer Cyclical ────────────────────────────────────────
  AMZN:  { sector: 'Consumer Cyclical', industry: 'Internet Retail' },
  SHOP:  { sector: 'Consumer Cyclical', industry: 'Internet Retail' },
  MELI:  { sector: 'Consumer Cyclical', industry: 'Internet Retail' },
  EBAY:  { sector: 'Consumer Cyclical', industry: 'Internet Retail' },
  ETSY:  { sector: 'Consumer Cyclical', industry: 'Internet Retail' },
  W:     { sector: 'Consumer Cyclical', industry: 'Internet Retail' },
  TSLA:  { sector: 'Consumer Cyclical', industry: 'Auto Manufacturers' },
  GM:    { sector: 'Consumer Cyclical', industry: 'Auto Manufacturers' },
  F:     { sector: 'Consumer Cyclical', industry: 'Auto Manufacturers' },
  HMC:   { sector: 'Consumer Cyclical', industry: 'Auto Manufacturers' },
  TM:    { sector: 'Consumer Cyclical', industry: 'Auto Manufacturers' },
  RIVN:  { sector: 'Consumer Cyclical', industry: 'Auto Manufacturers' },
  MCD:   { sector: 'Consumer Cyclical', industry: 'Restaurants' },
  SBUX:  { sector: 'Consumer Cyclical', industry: 'Restaurants' },
  CMG:   { sector: 'Consumer Cyclical', industry: 'Restaurants' },
  YUM:   { sector: 'Consumer Cyclical', industry: 'Restaurants' },
  DPZ:   { sector: 'Consumer Cyclical', industry: 'Restaurants' },
  QSR:   { sector: 'Consumer Cyclical', industry: 'Restaurants' },
  DASH:  { sector: 'Consumer Cyclical', industry: 'Internet Retail' },
  UBER:  { sector: 'Consumer Cyclical', industry: 'Software—Application' },
  LYFT:  { sector: 'Consumer Cyclical', industry: 'Software—Application' },
  HD:    { sector: 'Consumer Cyclical', industry: 'Home Improvement Retail' },
  LOW:   { sector: 'Consumer Cyclical', industry: 'Home Improvement Retail' },
  TGT:   { sector: 'Consumer Cyclical', industry: 'Discount Stores' },
  COST:  { sector: 'Consumer Cyclical', industry: 'Discount Stores' },
  WMT:   { sector: 'Consumer Cyclical', industry: 'Discount Stores' },
  KR:    { sector: 'Consumer Cyclical', industry: 'Grocery Stores' },
  DG:    { sector: 'Consumer Cyclical', industry: 'Discount Stores' },
  DLTR:  { sector: 'Consumer Cyclical', industry: 'Discount Stores' },
  NKE:   { sector: 'Consumer Cyclical', industry: 'Footwear & Accessories' },
  VFC:   { sector: 'Consumer Cyclical', industry: 'Apparel Manufacturing' },
  RL:    { sector: 'Consumer Cyclical', industry: 'Apparel Manufacturing' },
  PVH:   { sector: 'Consumer Cyclical', industry: 'Apparel Manufacturing' },
  BKNG:  { sector: 'Consumer Cyclical', industry: 'Travel Services' },
  ABNB:  { sector: 'Consumer Cyclical', industry: 'Travel Services' },
  EXPE:  { sector: 'Consumer Cyclical', industry: 'Travel Services' },
  TRIP:  { sector: 'Consumer Cyclical', industry: 'Travel Services' },
  MAR:   { sector: 'Consumer Cyclical', industry: 'Lodging' },
  HLT:   { sector: 'Consumer Cyclical', industry: 'Lodging' },
  H:     { sector: 'Consumer Cyclical', industry: 'Lodging' },
  TJX:   { sector: 'Consumer Cyclical', industry: 'Apparel Retail' },
  ROST:  { sector: 'Consumer Cyclical', industry: 'Apparel Retail' },
  GAP:   { sector: 'Consumer Cyclical', industry: 'Apparel Retail' },
  DHI:   { sector: 'Consumer Cyclical', industry: 'Residential Construction' },
  LEN:   { sector: 'Consumer Cyclical', industry: 'Residential Construction' },
  PHM:   { sector: 'Consumer Cyclical', industry: 'Residential Construction' },
  TOL:   { sector: 'Consumer Cyclical', industry: 'Residential Construction' },
  CPRT:  { sector: 'Consumer Cyclical', industry: 'Auto & Truck Dealerships' },
  AN:    { sector: 'Consumer Cyclical', industry: 'Auto & Truck Dealerships' },
  PAG:   { sector: 'Consumer Cyclical', industry: 'Auto & Truck Dealerships' },
  AZO:   { sector: 'Consumer Cyclical', industry: 'Specialty Retail' },
  ORLY:  { sector: 'Consumer Cyclical', industry: 'Specialty Retail' },
  BBY:   { sector: 'Consumer Cyclical', industry: 'Specialty Retail' },
  TSCO:  { sector: 'Consumer Cyclical', industry: 'Specialty Retail' },
  LVS:   { sector: 'Consumer Cyclical', industry: 'Resorts & Casinos' },
  MGM:   { sector: 'Consumer Cyclical', industry: 'Resorts & Casinos' },
  WYNN:  { sector: 'Consumer Cyclical', industry: 'Resorts & Casinos' },
  CCL:   { sector: 'Consumer Cyclical', industry: 'Travel Services' },
  RCL:   { sector: 'Consumer Cyclical', industry: 'Travel Services' },
  NCLH:  { sector: 'Consumer Cyclical', industry: 'Travel Services' },
  CTAS:  { sector: 'Industrials', industry: 'Specialty Business Services' },

  // ── Consumer Defensive ───────────────────────────────────────
  WMT2:  { sector: 'Consumer Defensive', industry: 'Discount Stores' },
  PG:    { sector: 'Consumer Defensive', industry: 'Household & Personal Products' },
  KO:    { sector: 'Consumer Defensive', industry: 'Beverages—Non-Alcoholic' },
  PEP:   { sector: 'Consumer Defensive', industry: 'Beverages—Non-Alcoholic' },
  KDP:   { sector: 'Consumer Defensive', industry: 'Beverages—Non-Alcoholic' },
  MNST:  { sector: 'Consumer Defensive', industry: 'Beverages—Non-Alcoholic' },
  STZ:   { sector: 'Consumer Defensive', industry: 'Beverages—Alcoholic' },
  TAP:   { sector: 'Consumer Defensive', industry: 'Beverages—Alcoholic' },
  ABEV:  { sector: 'Consumer Defensive', industry: 'Beverages—Alcoholic' },
  MDLZ:  { sector: 'Consumer Defensive', industry: 'Packaged Foods' },
  K:     { sector: 'Consumer Defensive', industry: 'Packaged Foods' },
  GIS:   { sector: 'Consumer Defensive', industry: 'Packaged Foods' },
  CPB:   { sector: 'Consumer Defensive', industry: 'Packaged Foods' },
  SJM:   { sector: 'Consumer Defensive', industry: 'Packaged Foods' },
  ADM:   { sector: 'Consumer Defensive', industry: 'Farm Products' },
  CAG:   { sector: 'Consumer Defensive', industry: 'Packaged Foods' },
  HRL:   { sector: 'Consumer Defensive', industry: 'Packaged Foods' },
  MKC:   { sector: 'Consumer Defensive', industry: 'Packaged Foods' },
  CLX:   { sector: 'Consumer Defensive', industry: 'Household & Personal Products' },
  KMB:   { sector: 'Consumer Defensive', industry: 'Household & Personal Products' },
  CHD:   { sector: 'Consumer Defensive', industry: 'Household & Personal Products' },
  EL:    { sector: 'Consumer Defensive', industry: 'Household & Personal Products' },
  UL:    { sector: 'Consumer Defensive', industry: 'Household & Personal Products' },
  PM:    { sector: 'Consumer Defensive', industry: 'Tobacco' },
  BTI:   { sector: 'Consumer Defensive', industry: 'Tobacco' },
  MO:    { sector: 'Consumer Defensive', industry: 'Tobacco' },
  WBA:   { sector: 'Consumer Defensive', industry: 'Pharmaceutical Retailers' },
  CVS:   { sector: 'Healthcare', industry: 'Healthcare Plans' },

  // ── Financial Services ───────────────────────────────────────
  JPM:   { sector: 'Financial Services', industry: 'Banks—Diversified' },
  BAC:   { sector: 'Financial Services', industry: 'Banks—Diversified' },
  WFC:   { sector: 'Financial Services', industry: 'Banks—Diversified' },
  C:     { sector: 'Financial Services', industry: 'Banks—Diversified' },
  USB:   { sector: 'Financial Services', industry: 'Banks—Regional' },
  PNC:   { sector: 'Financial Services', industry: 'Banks—Regional' },
  TFC:   { sector: 'Financial Services', industry: 'Banks—Regional' },
  BK:    { sector: 'Financial Services', industry: 'Asset Management' },
  HSBC:  { sector: 'Financial Services', industry: 'Banks—Diversified' },
  HDB:   { sector: 'Financial Services', industry: 'Banks—Diversified' },
  RY:    { sector: 'Financial Services', industry: 'Banks—Diversified' },
  UBS:   { sector: 'Financial Services', industry: 'Banks—Diversified' },
  SMFG:  { sector: 'Financial Services', industry: 'Banks—Diversified' },
  BBVA:  { sector: 'Financial Services', industry: 'Banks—Diversified' },
  BNS:   { sector: 'Financial Services', industry: 'Banks—Diversified' },
  BCS:   { sector: 'Financial Services', industry: 'Banks—Diversified' },
  BMO:   { sector: 'Financial Services', industry: 'Banks—Diversified' },
  TD:    { sector: 'Financial Services', industry: 'Banks—Diversified' },
  ITUB:  { sector: 'Financial Services', industry: 'Banks—Diversified' },
  LYG:   { sector: 'Financial Services', industry: 'Banks—Diversified' },
  NWG:   { sector: 'Financial Services', industry: 'Banks—Diversified' },
  NU:    { sector: 'Financial Services', industry: 'Banks—Diversified' },
  GS:    { sector: 'Financial Services', industry: 'Capital Markets' },
  MS:    { sector: 'Financial Services', industry: 'Capital Markets' },
  SCHW:  { sector: 'Financial Services', industry: 'Capital Markets' },
  SPGI:  { sector: 'Financial Services', industry: 'Capital Markets' },
  ICE:   { sector: 'Financial Services', industry: 'Capital Markets' },
  CME:   { sector: 'Financial Services', industry: 'Capital Markets' },
  NDAQ:  { sector: 'Financial Services', industry: 'Capital Markets' },
  CBOE:  { sector: 'Financial Services', industry: 'Capital Markets' },
  MORN:  { sector: 'Financial Services', industry: 'Capital Markets' },
  MCO:   { sector: 'Financial Services', industry: 'Capital Markets' },
  MSCI:  { sector: 'Financial Services', industry: 'Capital Markets' },
  V:     { sector: 'Financial Services', industry: 'Credit Services' },
  MA:    { sector: 'Financial Services', industry: 'Credit Services' },
  AXP:   { sector: 'Financial Services', industry: 'Credit Services' },
  COF:   { sector: 'Financial Services', industry: 'Credit Services' },
  SYF:   { sector: 'Financial Services', industry: 'Credit Services' },
  DFS:   { sector: 'Financial Services', industry: 'Credit Services' },
  PYPL:  { sector: 'Financial Services', industry: 'Credit Services' },
  FIS:   { sector: 'Financial Services', industry: 'Information Technology Services' },
  FISV:  { sector: 'Financial Services', industry: 'Information Technology Services' },
  GPN:   { sector: 'Financial Services', industry: 'Information Technology Services' },
  BRK_B: { sector: 'Financial Services', industry: 'Insurance—Diversified' },
  'BRK.B': { sector: 'Financial Services', industry: 'Insurance—Diversified' },
  PRU:   { sector: 'Financial Services', industry: 'Insurance—Life' },
  HIG:   { sector: 'Financial Services', industry: 'Insurance—Property & Casualty' },
  WRB:   { sector: 'Financial Services', industry: 'Insurance—Property & Casualty' },
  PFG:   { sector: 'Financial Services', industry: 'Insurance—Life' },
  AFL:   { sector: 'Financial Services', industry: 'Insurance—Life' },
  GL:    { sector: 'Financial Services', industry: 'Insurance—Life' },
  ALL:   { sector: 'Financial Services', industry: 'Insurance—Property & Casualty' },
  CB:    { sector: 'Financial Services', industry: 'Insurance—Property & Casualty' },
  MET:   { sector: 'Financial Services', industry: 'Insurance—Life' },
  TRV:   { sector: 'Financial Services', industry: 'Insurance—Property & Casualty' },
  PGR:   { sector: 'Financial Services', industry: 'Insurance—Property & Casualty' },
  AON:   { sector: 'Financial Services', industry: 'Insurance Brokers' },
  MMC:   { sector: 'Financial Services', industry: 'Insurance Brokers' },
  AJG:   { sector: 'Financial Services', industry: 'Insurance Brokers' },
  BLK:   { sector: 'Financial Services', industry: 'Asset Management' },
  BX:    { sector: 'Financial Services', industry: 'Asset Management' },
  APO:   { sector: 'Financial Services', industry: 'Asset Management' },
  ARES:  { sector: 'Financial Services', industry: 'Asset Management' },
  KKR:   { sector: 'Financial Services', industry: 'Asset Management' },
  CG:    { sector: 'Financial Services', industry: 'Asset Management' },

  // ── Healthcare ───────────────────────────────────────────────
  LLY:   { sector: 'Healthcare', industry: 'Drug Manufacturers—General' },
  JNJ:   { sector: 'Healthcare', industry: 'Drug Manufacturers—General' },
  PFE:   { sector: 'Healthcare', industry: 'Drug Manufacturers—General' },
  ABBV:  { sector: 'Healthcare', industry: 'Drug Manufacturers—General' },
  MRK:   { sector: 'Healthcare', industry: 'Drug Manufacturers—General' },
  BMY:   { sector: 'Healthcare', industry: 'Drug Manufacturers—General' },
  NVS:   { sector: 'Healthcare', industry: 'Drug Manufacturers—General' },
  AZN:   { sector: 'Healthcare', industry: 'Drug Manufacturers—General' },
  GSK:   { sector: 'Healthcare', industry: 'Drug Manufacturers—General' },
  SNY:   { sector: 'Healthcare', industry: 'Drug Manufacturers—General' },
  NVO:   { sector: 'Healthcare', industry: 'Drug Manufacturers—General' },
  TAK:   { sector: 'Healthcare', industry: 'Drug Manufacturers—General' },
  AMGN:  { sector: 'Healthcare', industry: 'Biotechnology' },
  GILD:  { sector: 'Healthcare', industry: 'Biotechnology' },
  REGN:  { sector: 'Healthcare', industry: 'Biotechnology' },
  VRTX:  { sector: 'Healthcare', industry: 'Biotechnology' },
  BIIB:  { sector: 'Healthcare', industry: 'Biotechnology' },
  ALNY:  { sector: 'Healthcare', industry: 'Biotechnology' },
  MRNA:  { sector: 'Healthcare', industry: 'Biotechnology' },
  BNTX:  { sector: 'Healthcare', industry: 'Biotechnology' },
  INCY:  { sector: 'Healthcare', industry: 'Biotechnology' },
  SGEN:  { sector: 'Healthcare', industry: 'Biotechnology' },
  ABT:   { sector: 'Healthcare', industry: 'Medical Devices' },
  BSX:   { sector: 'Healthcare', industry: 'Medical Devices' },
  ISRG:  { sector: 'Healthcare', industry: 'Medical Devices' },
  MDT:   { sector: 'Healthcare', industry: 'Medical Devices' },
  EW:    { sector: 'Healthcare', industry: 'Medical Devices' },
  ZBH:   { sector: 'Healthcare', industry: 'Medical Devices' },
  HOLX:  { sector: 'Healthcare', industry: 'Medical Devices' },
  ALGN:  { sector: 'Healthcare', industry: 'Medical Devices' },
  BAX:   { sector: 'Healthcare', industry: 'Medical Devices' },
  DXCM:  { sector: 'Healthcare', industry: 'Medical Devices' },
  STE:   { sector: 'Healthcare', industry: 'Medical Devices' },
  GEHC:  { sector: 'Healthcare', industry: 'Medical Devices' },
  RMD:   { sector: 'Healthcare', industry: 'Medical Devices' },
  ZTS:   { sector: 'Healthcare', industry: 'Medical Devices' },
  SYK:   { sector: 'Healthcare', industry: 'Medical Devices' },
  BDX:   { sector: 'Healthcare', industry: 'Medical Devices' },
  UNH:   { sector: 'Healthcare', industry: 'Healthcare Plans' },
  CI:    { sector: 'Healthcare', industry: 'Healthcare Plans' },
  HUM:   { sector: 'Healthcare', industry: 'Healthcare Plans' },
  ELV:   { sector: 'Healthcare', industry: 'Healthcare Plans' },
  HCA:   { sector: 'Healthcare', industry: 'Medical Care Facilities' },
  CNC:   { sector: 'Healthcare', industry: 'Healthcare Plans' },
  MOH:   { sector: 'Healthcare', industry: 'Healthcare Plans' },
  TMO:   { sector: 'Healthcare', industry: 'Diagnostics & Research' },
  DHR:   { sector: 'Healthcare', industry: 'Diagnostics & Research' },
  MCK:   { sector: 'Healthcare', industry: 'Medical Distribution' },
  CAH:   { sector: 'Healthcare', industry: 'Medical Distribution' },
  ABC:   { sector: 'Healthcare', industry: 'Medical Distribution' },
  IQVIA: { sector: 'Healthcare', industry: 'Diagnostics & Research' },
  IQV:   { sector: 'Healthcare', industry: 'Diagnostics & Research' },
  A:     { sector: 'Healthcare', industry: 'Diagnostics & Research' },
  MTD:   { sector: 'Healthcare', industry: 'Diagnostics & Research' },
  WAT:   { sector: 'Healthcare', industry: 'Diagnostics & Research' },
  LH:    { sector: 'Healthcare', industry: 'Diagnostics & Research' },
  DGX:   { sector: 'Healthcare', industry: 'Diagnostics & Research' },
  DVA:   { sector: 'Healthcare', industry: 'Medical Care Facilities' },
  VTRS:  { sector: 'Healthcare', industry: 'Drug Manufacturers—Specialty & Generic' },
  TEVA:  { sector: 'Healthcare', industry: 'Drug Manufacturers—Specialty & Generic' },

  // ── Energy ───────────────────────────────────────────────────
  XOM:   { sector: 'Energy', industry: 'Oil & Gas Integrated' },
  CVX:   { sector: 'Energy', industry: 'Oil & Gas Integrated' },
  SHEL:  { sector: 'Energy', industry: 'Oil & Gas Integrated' },
  TTE:   { sector: 'Energy', industry: 'Oil & Gas Integrated' },
  BP:    { sector: 'Energy', industry: 'Oil & Gas Integrated' },
  EQNR:  { sector: 'Energy', industry: 'Oil & Gas Integrated' },
  COP:   { sector: 'Energy', industry: 'Oil & Gas E&P' },
  EOG:   { sector: 'Energy', industry: 'Oil & Gas E&P' },
  PXD:   { sector: 'Energy', industry: 'Oil & Gas E&P' },
  DVN:   { sector: 'Energy', industry: 'Oil & Gas E&P' },
  FANG:  { sector: 'Energy', industry: 'Oil & Gas E&P' },
  APA:   { sector: 'Energy', industry: 'Oil & Gas E&P' },
  MRO:   { sector: 'Energy', industry: 'Oil & Gas E&P' },
  CNQ:   { sector: 'Energy', industry: 'Oil & Gas E&P' },
  OXY:   { sector: 'Energy', industry: 'Oil & Gas E&P' },
  PSX:   { sector: 'Energy', industry: 'Oil & Gas Refining & Marketing' },
  VLO:   { sector: 'Energy', industry: 'Oil & Gas Refining & Marketing' },
  MPC:   { sector: 'Energy', industry: 'Oil & Gas Refining & Marketing' },
  HAL:   { sector: 'Energy', industry: 'Oil & Gas Equipment & Services' },
  SLB:   { sector: 'Energy', industry: 'Oil & Gas Equipment & Services' },
  BKR:   { sector: 'Energy', industry: 'Oil & Gas Equipment & Services' },
  ENB:   { sector: 'Energy', industry: 'Oil & Gas Midstream' },
  KMI:   { sector: 'Energy', industry: 'Oil & Gas Midstream' },
  ET:    { sector: 'Energy', industry: 'Oil & Gas Midstream' },
  WMB:   { sector: 'Energy', industry: 'Oil & Gas Midstream' },
  OKE:   { sector: 'Energy', industry: 'Oil & Gas Midstream' },
  TRP:   { sector: 'Energy', industry: 'Oil & Gas Midstream' },
  LNG:   { sector: 'Energy', industry: 'Oil & Gas Midstream' },
  CTRA:  { sector: 'Energy', industry: 'Oil & Gas E&P' },

  // ── Industrials ──────────────────────────────────────────────
  BA:    { sector: 'Industrials', industry: 'Aerospace & Defense' },
  RTX:   { sector: 'Industrials', industry: 'Aerospace & Defense' },
  LMT:   { sector: 'Industrials', industry: 'Aerospace & Defense' },
  NOC:   { sector: 'Industrials', industry: 'Aerospace & Defense' },
  GD:    { sector: 'Industrials', industry: 'Aerospace & Defense' },
  HWM:   { sector: 'Industrials', industry: 'Aerospace & Defense' },
  TDG:   { sector: 'Industrials', industry: 'Aerospace & Defense' },
  LHX:   { sector: 'Industrials', industry: 'Aerospace & Defense' },
  LDOS:  { sector: 'Industrials', industry: 'Aerospace & Defense' },
  SAIC:  { sector: 'Industrials', industry: 'Aerospace & Defense' },
  L3H:   { sector: 'Industrials', industry: 'Aerospace & Defense' },
  HEI:   { sector: 'Industrials', industry: 'Aerospace & Defense' },
  CAT:   { sector: 'Industrials', industry: 'Farm & Heavy Construction Machinery' },
  DE:    { sector: 'Industrials', industry: 'Farm & Heavy Construction Machinery' },
  AGCO:  { sector: 'Industrials', industry: 'Farm & Heavy Construction Machinery' },
  MMM:   { sector: 'Industrials', industry: 'Specialty Industrial Machinery' },
  GE:    { sector: 'Industrials', industry: 'Specialty Industrial Machinery' },
  GEV:   { sector: 'Industrials', industry: 'Specialty Industrial Machinery' },
  HON:   { sector: 'Industrials', industry: 'Specialty Industrial Machinery' },
  AME:   { sector: 'Industrials', industry: 'Specialty Industrial Machinery' },
  ITW:   { sector: 'Industrials', industry: 'Specialty Industrial Machinery' },
  ETN:   { sector: 'Industrials', industry: 'Specialty Industrial Machinery' },
  EMR:   { sector: 'Industrials', industry: 'Specialty Industrial Machinery' },
  PH:    { sector: 'Industrials', industry: 'Specialty Industrial Machinery' },
  IR:    { sector: 'Industrials', industry: 'Specialty Industrial Machinery' },
  FTV:   { sector: 'Industrials', industry: 'Specialty Industrial Machinery' },
  ROK:   { sector: 'Industrials', industry: 'Specialty Industrial Machinery' },
  DOV:   { sector: 'Industrials', industry: 'Specialty Industrial Machinery' },
  ROP:   { sector: 'Industrials', industry: 'Specialty Industrial Machinery' },
  IEX:   { sector: 'Industrials', industry: 'Specialty Industrial Machinery' },
  GNRC:  { sector: 'Industrials', industry: 'Specialty Industrial Machinery' },
  XYL:   { sector: 'Industrials', industry: 'Specialty Industrial Machinery' },
  SWK:   { sector: 'Industrials', industry: 'Tools & Accessories' },
  FLR:   { sector: 'Industrials', industry: 'Engineering & Construction' },
  PWR:   { sector: 'Industrials', industry: 'Engineering & Construction' },
  J:     { sector: 'Industrials', industry: 'Engineering & Construction' },
  UPS:   { sector: 'Industrials', industry: 'Integrated Freight & Logistics' },
  FDX:   { sector: 'Industrials', industry: 'Integrated Freight & Logistics' },
  XPO:   { sector: 'Industrials', industry: 'Integrated Freight & Logistics' },
  CHRW:  { sector: 'Industrials', industry: 'Integrated Freight & Logistics' },
  EXPD:  { sector: 'Industrials', industry: 'Integrated Freight & Logistics' },
  ODFL:  { sector: 'Industrials', industry: 'Trucking' },
  JBHT:  { sector: 'Industrials', industry: 'Trucking' },
  UNP:   { sector: 'Industrials', industry: 'Railroads' },
  CSX:   { sector: 'Industrials', industry: 'Railroads' },
  NSC:   { sector: 'Industrials', industry: 'Railroads' },
  CNI:   { sector: 'Industrials', industry: 'Railroads' },
  CP:    { sector: 'Industrials', industry: 'Railroads' },
  DAL:   { sector: 'Industrials', industry: 'Airlines' },
  UAL:   { sector: 'Industrials', industry: 'Airlines' },
  AAL:   { sector: 'Industrials', industry: 'Airlines' },
  LUV:   { sector: 'Industrials', industry: 'Airlines' },
  RSG:   { sector: 'Industrials', industry: 'Waste Management' },
  WM:    { sector: 'Industrials', industry: 'Waste Management' },
  CTAS:  { sector: 'Industrials', industry: 'Specialty Business Services' },
  FAST:  { sector: 'Industrials', industry: 'Industrial Distribution' },
  GWW:   { sector: 'Industrials', industry: 'Industrial Distribution' },
  MSC:   { sector: 'Industrials', industry: 'Industrial Distribution' },
  SNA:   { sector: 'Industrials', industry: 'Tools & Accessories' },
  MAS:   { sector: 'Industrials', industry: 'Building Products & Equipment' },
  AOS:   { sector: 'Industrials', industry: 'Building Products & Equipment' },
  CARR:  { sector: 'Industrials', industry: 'Building Products & Equipment' },
  OTIS:  { sector: 'Industrials', industry: 'Specialty Industrial Machinery' },
  VRSK:  { sector: 'Industrials', industry: 'Consulting Services' },
  BR:    { sector: 'Industrials', industry: 'Information Technology Services' },
  TT:    { sector: 'Industrials', industry: 'Building Products & Equipment' },
  PAYC:  { sector: 'Industrials', industry: 'Software—Application' },
  AYI:   { sector: 'Industrials', industry: 'Electrical Equipment & Parts' },
  NDSN:  { sector: 'Industrials', industry: 'Specialty Industrial Machinery' },
  ALK:   { sector: 'Industrials', industry: 'Airlines' },
  ALLE:  { sector: 'Industrials', industry: 'Security & Protection Services' },
  EXPO:  { sector: 'Industrials', industry: 'Industrial Distribution' },

  // ── Basic Materials ──────────────────────────────────────────
  LIN:   { sector: 'Basic Materials', industry: 'Specialty Chemicals' },
  ECL:   { sector: 'Basic Materials', industry: 'Specialty Chemicals' },
  APD:   { sector: 'Basic Materials', industry: 'Specialty Chemicals' },
  SHW:   { sector: 'Basic Materials', industry: 'Specialty Chemicals' },
  DD:    { sector: 'Basic Materials', industry: 'Specialty Chemicals' },
  DOW:   { sector: 'Basic Materials', industry: 'Specialty Chemicals' },
  ALB:   { sector: 'Basic Materials', industry: 'Specialty Chemicals' },
  PPG:   { sector: 'Basic Materials', industry: 'Specialty Chemicals' },
  IFF:   { sector: 'Basic Materials', industry: 'Specialty Chemicals' },
  RPM:   { sector: 'Basic Materials', industry: 'Specialty Chemicals' },
  CE:    { sector: 'Basic Materials', industry: 'Specialty Chemicals' },
  EMN:   { sector: 'Basic Materials', industry: 'Specialty Chemicals' },
  FCX:   { sector: 'Basic Materials', industry: 'Copper' },
  NEM:   { sector: 'Basic Materials', industry: 'Gold' },
  AEM:   { sector: 'Basic Materials', industry: 'Gold' },
  GFI:   { sector: 'Basic Materials', industry: 'Gold' },
  AU:    { sector: 'Basic Materials', industry: 'Gold' },
  CDE:   { sector: 'Basic Materials', industry: 'Silver' },
  PAAS:  { sector: 'Basic Materials', industry: 'Silver' },
  RIO:   { sector: 'Basic Materials', industry: 'Other Industrial Metals & Mining' },
  BHP:   { sector: 'Basic Materials', industry: 'Other Industrial Metals & Mining' },
  VALE:  { sector: 'Basic Materials', industry: 'Other Industrial Metals & Mining' },
  SCCO:  { sector: 'Basic Materials', industry: 'Copper' },
  IP:    { sector: 'Basic Materials', industry: 'Paper & Paper Products' },
  PKG:   { sector: 'Basic Materials', industry: 'Packaging & Containers' },
  NUE:   { sector: 'Basic Materials', industry: 'Steel' },
  STLD:  { sector: 'Basic Materials', industry: 'Steel' },
  CLF:   { sector: 'Basic Materials', industry: 'Steel' },
  RS:    { sector: 'Basic Materials', industry: 'Steel' },
  VMC:   { sector: 'Basic Materials', industry: 'Building Materials' },
  MLM:   { sector: 'Basic Materials', industry: 'Building Materials' },
  CRH:   { sector: 'Basic Materials', industry: 'Building Materials' },

  // ── Real Estate ──────────────────────────────────────────────
  PLD:   { sector: 'Real Estate', industry: 'REIT—Industrial' },
  AMT:   { sector: 'Real Estate', industry: 'REIT—Specialty' },
  EQIX:  { sector: 'Real Estate', industry: 'REIT—Specialty' },
  WELL:  { sector: 'Real Estate', industry: 'REIT—Healthcare Facilities' },
  O:     { sector: 'Real Estate', industry: 'REIT—Retail' },
  PSA:   { sector: 'Real Estate', industry: 'REIT—Industrial' },
  SPG:   { sector: 'Real Estate', industry: 'REIT—Retail' },
  VICI:  { sector: 'Real Estate', industry: 'REIT—Specialty' },
  CCI:   { sector: 'Real Estate', industry: 'REIT—Specialty' },
  DLR:   { sector: 'Real Estate', industry: 'REIT—Specialty' },
  EQR:   { sector: 'Real Estate', industry: 'REIT—Residential' },
  AVB:   { sector: 'Real Estate', industry: 'REIT—Residential' },
  ARE:   { sector: 'Real Estate', industry: 'REIT—Office' },
  BXP:   { sector: 'Real Estate', industry: 'REIT—Office' },
  EXR:   { sector: 'Real Estate', industry: 'REIT—Industrial' },
  INVH:  { sector: 'Real Estate', industry: 'REIT—Residential' },
  AMH:   { sector: 'Real Estate', industry: 'REIT—Residential' },

  // ── Utilities ────────────────────────────────────────────────
  NEE:   { sector: 'Utilities', industry: 'Utilities—Renewable' },
  SO:    { sector: 'Utilities', industry: 'Utilities—Regulated Electric' },
  DUK:   { sector: 'Utilities', industry: 'Utilities—Regulated Electric' },
  AEP:   { sector: 'Utilities', industry: 'Utilities—Regulated Electric' },
  XEL:   { sector: 'Utilities', industry: 'Utilities—Regulated Electric' },
  EXC:   { sector: 'Utilities', industry: 'Utilities—Regulated Electric' },
  ED:    { sector: 'Utilities', industry: 'Utilities—Regulated Electric' },
  ES:    { sector: 'Utilities', industry: 'Utilities—Regulated Electric' },
  AES:   { sector: 'Utilities', industry: 'Utilities—Regulated Electric' },
  CEG:   { sector: 'Utilities', industry: 'Utilities—Renewable' },
  PCG:   { sector: 'Utilities', industry: 'Utilities—Regulated Electric' },
  EIX:   { sector: 'Utilities', industry: 'Utilities—Regulated Electric' },
  WEC:   { sector: 'Utilities', industry: 'Utilities—Regulated Electric' },
  AWK:   { sector: 'Utilities', industry: 'Utilities—Regulated Water' },
  NI:    { sector: 'Utilities', industry: 'Utilities—Regulated Gas' },
  CMS:   { sector: 'Utilities', industry: 'Utilities—Regulated Electric' },
  LNT:   { sector: 'Utilities', industry: 'Utilities—Regulated Electric' },
  ETR:   { sector: 'Utilities', industry: 'Utilities—Regulated Electric' },
  AEE:   { sector: 'Utilities', industry: 'Utilities—Regulated Electric' },
  PPL:   { sector: 'Utilities', industry: 'Utilities—Regulated Electric' },
  FE:    { sector: 'Utilities', industry: 'Utilities—Regulated Electric' },
  EVRG:  { sector: 'Utilities', industry: 'Utilities—Regulated Electric' },
  SRE:   { sector: 'Utilities', industry: 'Utilities—Diversified' },
  D:     { sector: 'Utilities', industry: 'Utilities—Regulated Electric' },
  PEG:   { sector: 'Utilities', industry: 'Utilities—Regulated Electric' },
  NRG:   { sector: 'Utilities', industry: 'Utilities—Independent Power Producers' },
  VST:   { sector: 'Utilities', industry: 'Utilities—Independent Power Producers' },

  // ── Missing: Financial Services ──────────────────────────────
  ACGL:  { sector: 'Financial Services', industry: 'Insurance—Property & Casualty' },
  AIZ:   { sector: 'Financial Services', industry: 'Insurance—Specialty' },
  AMP:   { sector: 'Financial Services', industry: 'Asset Management' },
  BAM:   { sector: 'Financial Services', industry: 'Asset Management' },
  BEN:   { sector: 'Financial Services', industry: 'Asset Management' },
  BRO:   { sector: 'Financial Services', industry: 'Insurance Brokers' },
  CBRE:  { sector: 'Real Estate', industry: 'Real Estate Services' },
  CFG:   { sector: 'Financial Services', industry: 'Banks—Regional' },
  CPAY:  { sector: 'Financial Services', industry: 'Credit Services' },
  CRCL:  { sector: 'Financial Services', industry: 'Credit Services' },
  EFX:   { sector: 'Industrials', industry: 'Consulting Services' },
  ERIE:  { sector: 'Financial Services', industry: 'Insurance—Property & Casualty' },
  FDS:   { sector: 'Financial Services', industry: 'Capital Markets' },
  FITB:  { sector: 'Financial Services', industry: 'Banks—Regional' },
  GBTC:  { sector: 'Financial Services', industry: 'Capital Markets' },
  HBAN:  { sector: 'Financial Services', industry: 'Banks—Regional' },
  HOOD:  { sector: 'Financial Services', industry: 'Capital Markets' },
  IBKR:  { sector: 'Financial Services', industry: 'Capital Markets' },
  IVZ:   { sector: 'Financial Services', industry: 'Asset Management' },
  KEY:   { sector: 'Financial Services', industry: 'Banks—Regional' },
  MRSH:  { sector: 'Financial Services', industry: 'Insurance Brokers' },
  MSTR:  { sector: 'Technology', industry: 'Software—Application' },
  MTB:   { sector: 'Financial Services', industry: 'Banks—Regional' },
  MUFG:  { sector: 'Financial Services', industry: 'Banks—Diversified' },
  NTRS:  { sector: 'Financial Services', industry: 'Asset Management' },
  RF:    { sector: 'Financial Services', industry: 'Banks—Regional' },
  RJF:   { sector: 'Financial Services', industry: 'Capital Markets' },
  SAN:   { sector: 'Financial Services', industry: 'Banks—Diversified' },
  STT:   { sector: 'Financial Services', industry: 'Asset Management' },
  TROW:  { sector: 'Financial Services', industry: 'Asset Management' },
  WTW:   { sector: 'Financial Services', industry: 'Insurance Brokers' },

  // ── Missing: Technology ───────────────────────────────────────
  AKAM:  { sector: 'Technology', industry: 'Software—Application' },
  ANSS:  { sector: 'Technology', industry: 'Software—Application' },
  APP:   { sector: 'Technology', industry: 'Software—Application' },
  CIEN:  { sector: 'Technology', industry: 'Communication Equipment' },
  COHR:  { sector: 'Technology', industry: 'Electronic Components' },
  CSGP:  { sector: 'Real Estate', industry: 'Real Estate Services' },
  CRWV:  { sector: 'Technology', industry: 'Software—Application' },
  EPAM:  { sector: 'Technology', industry: 'Information Technology Services' },
  FFIV:  { sector: 'Technology', industry: 'Communication Equipment' },
  FIG:   { sector: 'Financial Services', industry: 'Asset Management' },
  FLUT:  { sector: 'Consumer Cyclical', industry: 'Gambling' },
  GDDY:  { sector: 'Technology', industry: 'Software—Application' },
  GEN:   { sector: 'Technology', industry: 'Software—Application' },
  GLW:   { sector: 'Technology', industry: 'Electronic Components' },
  GRMN:  { sector: 'Technology', industry: 'Scientific & Technical Instruments' },
  IT:    { sector: 'Technology', industry: 'Information Technology Services' },
  JBL:   { sector: 'Technology', industry: 'Electronic Components' },
  JKHY:  { sector: 'Technology', industry: 'Information Technology Services' },
  LITE:  { sector: 'Technology', industry: 'Electronic Components' },
  MSI:   { sector: 'Technology', industry: 'Communication Equipment' },
  PODD:  { sector: 'Healthcare', industry: 'Medical Devices' },
  PTC:   { sector: 'Technology', industry: 'Software—Application' },
  Q:     { sector: 'Technology', industry: 'Semiconductors' },
  RBLX:  { sector: 'Communication Services', industry: 'Entertainment' },
  SMCI:  { sector: 'Technology', industry: 'Computer Hardware' },
  SNDK:  { sector: 'Technology', industry: 'Computer Hardware' },
  TDY:   { sector: 'Industrials', industry: 'Aerospace & Defense' },
  TEL:   { sector: 'Technology', industry: 'Electronic Components' },
  TRMB:  { sector: 'Technology', industry: 'Scientific & Technical Instruments' },
  TTD:   { sector: 'Technology', industry: 'Software—Application' },
  TYL:   { sector: 'Technology', industry: 'Software—Application' },
  VLTO:  { sector: 'Industrials', industry: 'Specialty Industrial Machinery' },
  VRT:   { sector: 'Technology', industry: 'Electronic Components' },
  VRSN:  { sector: 'Technology', industry: 'Software—Application' },
  XYZ:   { sector: 'Technology', industry: 'Software—Application' },
  ZBRA:  { sector: 'Technology', industry: 'Scientific & Technical Instruments' },
  ZM:    { sector: 'Technology', industry: 'Software—Application' },

  // ── Missing: Consumer Cyclical ────────────────────────────────
  ANF:   { sector: 'Consumer Cyclical', industry: 'Apparel Retail' },
  APTV:  { sector: 'Consumer Cyclical', industry: 'Auto Parts' },
  ATVI:  { sector: 'Communication Services', industry: 'Entertainment' },
  BABA:  { sector: 'Consumer Cyclical', industry: 'Internet Retail' },
  CVNA:  { sector: 'Consumer Cyclical', industry: 'Auto & Truck Dealerships' },
  CZR:   { sector: 'Consumer Cyclical', industry: 'Resorts & Casinos' },
  DECK:  { sector: 'Consumer Cyclical', industry: 'Footwear & Accessories' },
  DRI:   { sector: 'Consumer Cyclical', industry: 'Restaurants' },
  GPC:   { sector: 'Consumer Cyclical', industry: 'Auto Parts' },
  GPS:   { sector: 'Consumer Cyclical', industry: 'Apparel Retail' },
  HAS:   { sector: 'Consumer Cyclical', industry: 'Leisure' },
  LULU:  { sector: 'Consumer Cyclical', industry: 'Apparel Retail' },
  LYV:   { sector: 'Communication Services', industry: 'Entertainment' },
  M:     { sector: 'Consumer Cyclical', industry: 'Department Stores' },
  PCAR:  { sector: 'Industrials', industry: 'Farm & Heavy Construction Machinery' },
  POOL:  { sector: 'Consumer Cyclical', industry: 'Specialty Retail' },
  ROL:   { sector: 'Consumer Cyclical', industry: 'Personal Services' },
  TCOM:  { sector: 'Consumer Cyclical', industry: 'Travel Services' },
  TKO:   { sector: 'Communication Services', industry: 'Entertainment' },
  TPR:   { sector: 'Consumer Cyclical', industry: 'Luxury Goods' },
  ULTA:  { sector: 'Consumer Cyclical', industry: 'Specialty Retail' },
  URBN:  { sector: 'Consumer Cyclical', industry: 'Apparel Retail' },
  JWN:   { sector: 'Consumer Cyclical', industry: 'Department Stores' },
  KSS:   { sector: 'Consumer Cyclical', industry: 'Department Stores' },

  // ── Missing: Consumer Defensive ──────────────────────────────
  BJ:    { sector: 'Consumer Defensive', industry: 'Discount Stores' },
  CL:    { sector: 'Consumer Defensive', industry: 'Household & Personal Products' },
  FRPT:  { sector: 'Consumer Defensive', industry: 'Packaged Foods' },
  HSY:   { sector: 'Consumer Defensive', industry: 'Packaged Foods' },
  KHC:   { sector: 'Consumer Defensive', industry: 'Packaged Foods' },
  KVUE:  { sector: 'Consumer Defensive', industry: 'Household & Personal Products' },
  TSN:   { sector: 'Consumer Defensive', industry: 'Packaged Foods' },

  // ── Missing: Industrials ──────────────────────────────────────
  AMCR:  { sector: 'Basic Materials', industry: 'Packaging & Containers' },
  AVY:   { sector: 'Industrials', industry: 'Packaging & Containers' },
  AXON:  { sector: 'Industrials', industry: 'Aerospace & Defense' },
  BALL:  { sector: 'Basic Materials', industry: 'Packaging & Containers' },
  BLDR:  { sector: 'Industrials', industry: 'Building Products & Equipment' },
  CMI:   { sector: 'Industrials', industry: 'Specialty Industrial Machinery' },
  CR:    { sector: 'Industrials', industry: 'Specialty Industrial Machinery' },
  CRL:   { sector: 'Healthcare', industry: 'Diagnostics & Research' },
  EME:   { sector: 'Industrials', industry: 'Engineering & Construction' },
  FERG:  { sector: 'Industrials', industry: 'Industrial Distribution' },
  FIX:   { sector: 'Industrials', industry: 'Engineering & Construction' },
  HII:   { sector: 'Industrials', industry: 'Aerospace & Defense' },
  JCI:   { sector: 'Industrials', industry: 'Building Products & Equipment' },
  LII:   { sector: 'Industrials', industry: 'Building Products & Equipment' },
  MNDT:  { sector: 'Technology', industry: 'Software—Application' },
  OMC:   { sector: 'Communication Services', industry: 'Advertising Agencies' },
  PAYX:  { sector: 'Industrials', industry: 'Staffing & Employment Services' },
  PNR:   { sector: 'Industrials', industry: 'Specialty Industrial Machinery' },
  RVTY:  { sector: 'Healthcare', industry: 'Diagnostics & Research' },
  SOLV:  { sector: 'Healthcare', industry: 'Medical Devices' },
  TXT:   { sector: 'Industrials', industry: 'Aerospace & Defense' },
  URI:   { sector: 'Industrials', industry: 'Rental & Leasing Services' },
  VLTO:  { sector: 'Industrials', industry: 'Specialty Industrial Machinery' },
  WAB:   { sector: 'Industrials', industry: 'Specialty Industrial Machinery' },

  // ── Missing: Energy ───────────────────────────────────────────
  ATO:   { sector: 'Utilities', industry: 'Utilities—Regulated Gas' },
  EPD:   { sector: 'Energy', industry: 'Oil & Gas Midstream' },
  EQT:   { sector: 'Energy', industry: 'Oil & Gas E&P' },
  EXE:   { sector: 'Energy', industry: 'Oil & Gas E&P' },
  MPLX:  { sector: 'Energy', industry: 'Oil & Gas Midstream' },
  NTR:   { sector: 'Basic Materials', industry: 'Agricultural Inputs' },
  PAA:   { sector: 'Energy', industry: 'Oil & Gas Midstream' },
  SQM:   { sector: 'Basic Materials', industry: 'Agricultural Inputs' },
  TPL:   { sector: 'Energy', industry: 'Oil & Gas E&P' },
  TRGP:  { sector: 'Energy', industry: 'Oil & Gas Midstream' },

  // ── Missing: Real Estate ──────────────────────────────────────
  CPT:   { sector: 'Real Estate', industry: 'REIT—Residential' },
  DOC:   { sector: 'Real Estate', industry: 'REIT—Healthcare Facilities' },
  FRT:   { sector: 'Real Estate', industry: 'REIT—Retail' },
  HIW:   { sector: 'Real Estate', industry: 'REIT—Office' },
  HST:   { sector: 'Real Estate', industry: 'REIT—Hotel & Motel' },
  IRM:   { sector: 'Real Estate', industry: 'REIT—Specialty' },
  KIM:   { sector: 'Real Estate', industry: 'REIT—Retail' },
  KRC:   { sector: 'Real Estate', industry: 'REIT—Office' },
  LAMR:  { sector: 'Real Estate', industry: 'REIT—Specialty' },
  MAA:   { sector: 'Real Estate', industry: 'REIT—Residential' },
  PEAK:  { sector: 'Real Estate', industry: 'REIT—Healthcare Facilities' },
  REG:   { sector: 'Real Estate', industry: 'REIT—Retail' },
  SBAC:  { sector: 'Real Estate', industry: 'REIT—Specialty' },
  UDR:   { sector: 'Real Estate', industry: 'REIT—Residential' },
  WY:    { sector: 'Real Estate', industry: 'REIT—Specialty' },

  // ── Missing: Utilities ────────────────────────────────────────
  CNP:   { sector: 'Utilities', industry: 'Utilities—Regulated Gas' },
  PNW:   { sector: 'Utilities', industry: 'Utilities—Regulated Electric' },

  // ── Missing: Basic Materials ──────────────────────────────────
  AA:    { sector: 'Basic Materials', industry: 'Aluminum' },
  CF:    { sector: 'Basic Materials', industry: 'Agricultural Inputs' },
  CTVA:  { sector: 'Basic Materials', industry: 'Agricultural Inputs' },

  // ── Missing: Healthcare ───────────────────────────────────────
  ALC:   { sector: 'Healthcare', industry: 'Medical Devices' },
  HSIC:  { sector: 'Healthcare', industry: 'Medical Distribution' },
  NVAX:  { sector: 'Healthcare', industry: 'Biotechnology' },
  SRNE:  { sector: 'Healthcare', industry: 'Biotechnology' },
  TECH:  { sector: 'Healthcare', industry: 'Biotechnology' },

  // ── Missing: Communication Services ──────────────────────────
  NWSA:  { sector: 'Communication Services', industry: 'Entertainment' },
  PSKY:  { sector: 'Communication Services', industry: 'Entertainment' },
  SATS:  { sector: 'Communication Services', industry: 'Telecom Services' },

  // ── Misc / Other ─────────────────────────────────────────────
  ALC2:  { sector: 'Healthcare', industry: 'Medical Devices' },
  CLO:   { sector: 'Financial Services', industry: 'Asset Management' },
  CM:    { sector: 'Financial Services', industry: 'Banks—Diversified' },
  COR:   { sector: 'Healthcare', industry: 'Medical Distribution' },
  NXP:   { sector: 'Technology', industry: 'Semiconductors' },
  SJI:   { sector: 'Utilities', industry: 'Utilities—Regulated Gas' },
  CPNG:  { sector: 'Consumer Cyclical', industry: 'Internet Retail' },
  LUMN:  { sector: 'Communication Services', industry: 'Telecom Services' },
  WRK:   { sector: 'Basic Materials', industry: 'Packaging & Containers' },
};


// ─────────────────────────────────────────────────────────────
// DETECT SIC-STYLE (ALL CAPS) VALUES
// ─────────────────────────────────────────────────────────────
function isSicStyle(value: string | null): boolean {
  if (!value) return false;
  // ALL CAPS with spaces/punctuation, or sector === industry pattern
  const trimmed = value.trim();
  if (trimmed.length < 2) return false;
  // Check if more than 60% uppercase letters (SIC codes are fully uppercase)
  const letters = trimmed.replace(/[^a-zA-Z]/g, '');
  if (letters.length === 0) return false;
  const upperCount = (trimmed.match(/[A-Z]/g) || []).length;
  const ratio = upperCount / letters.length;
  return ratio > 0.7 && trimmed === trimmed.toUpperCase();
}

function needsFix(sector: string | null, industry: string | null): boolean {
  if (!sector || sector === 'Unknown' || sector === 'N/A') return true;
  if (!industry || industry === 'Unknown' || industry === 'N/A') return true;
  if (sector === industry) return true;
  if (isSicStyle(sector)) return true;
  if (isSicStyle(industry)) return true;
  return false;
}

// ─────────────────────────────────────────────────────────────
// MAIN
// ─────────────────────────────────────────────────────────────
async function fixSicIndustryData() {
  console.log('\n🔍 Scanning for SIC-style / incorrect sector+industry data...\n');

  const all = await prisma.ticker.findMany({
    select: { symbol: true, sector: true, industry: true },
    orderBy: { symbol: 'asc' },
  });

  console.log(`📊 Total tickers in DB: ${all.length}`);

  // Find problematic ones
  const problematic = all.filter(t => needsFix(t.sector, t.industry));
  console.log(`⚠️  Tickers needing fix: ${problematic.length}\n`);

  if (problematic.length === 0) {
    console.log('✅ All tickers look clean!');
    return;
  }

  let fixed = 0;
  let skipped = 0;
  const stillBad: string[] = [];

  for (const ticker of problematic) {
    const mapping = CORRECT_MAPPINGS[ticker.symbol];
    if (mapping) {
      await prisma.ticker.update({
        where: { symbol: ticker.symbol },
        data: { sector: mapping.sector, industry: mapping.industry, updatedAt: new Date() },
      });
      console.log(`  ✅ ${ticker.symbol.padEnd(8)} ${(ticker.sector || 'null').padEnd(30)} → ${mapping.sector} / ${mapping.industry}`);
      fixed++;
    } else {
      console.log(`  ⚠️  ${ticker.symbol.padEnd(8)} No mapping found (${ticker.sector || 'null'} / ${ticker.industry || 'null'})`);
      stillBad.push(ticker.symbol);
      skipped++;
    }
  }

  console.log('\n' + '═'.repeat(60));
  console.log(`✅ Fixed:   ${fixed}`);
  console.log(`⚠️  Skipped: ${skipped} (no mapping available)`);
  if (stillBad.length > 0) {
    console.log(`\n📋 Still needs manual mapping:\n   ${stillBad.join(', ')}`);
  }
  console.log('═'.repeat(60) + '\n');
}

fixSicIndustryData()
  .then(() => process.exit(0))
  .catch(e => { console.error(e); process.exit(1); });
